"""Create product_master, transactions and transaction_details tables

Revision ID: 75867baf3a62
Revises: 
Create Date: 2025-10-16 01:29:07.280870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75867baf3a62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_master',
    sa.Column('PRD_ID', sa.Integer(), autoincrement=True, nullable=False, comment='商品一意キー'),
    sa.Column('CODE', sa.String(length=25), nullable=False, comment='商品コード(バーコード)'),
    sa.Column('NAME', sa.String(length=50), nullable=False, comment='商品名称'),
    sa.Column('PRICE', sa.Integer(), nullable=False, comment='商品単価'),
    sa.PrimaryKeyConstraint('PRD_ID'),
    comment='商品マスタ'
    )
    op.create_index(op.f('ix_product_master_CODE'), 'product_master', ['CODE'], unique=True)
    op.create_table('transactions',
    sa.Column('TRD_ID', sa.Integer(), autoincrement=True, nullable=False, comment='取引一意キー'),
    sa.Column('DATETIME', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='取引日時'),
    sa.Column('EMP_CD', sa.String(length=10), nullable=True, comment='レジ担当者コード'),
    sa.Column('STORE_CD', sa.String(length=5), nullable=True, comment='店舗コード'),
    sa.Column('POS_NO', sa.String(length=3), nullable=True, comment='POS機ID'),
    sa.Column('TOTAL_AMT', sa.Integer(), nullable=True, comment='合計金額'),
    sa.Column('TTL_AMT_EX_TAX', sa.Integer(), nullable=True, comment='合計金額（税抜）'),
    sa.PrimaryKeyConstraint('TRD_ID'),
    comment='取引ヘッダ'
    )
    op.create_table('transaction_details',
    sa.Column('TRD_ID', sa.Integer(), nullable=False, comment='取引一意キー'),
    sa.Column('DTL_ID', sa.Integer(), nullable=False, comment='取引明細一意キー'),
    sa.Column('PRD_ID', sa.Integer(), nullable=False, comment='商品一意キー'),
    sa.Column('PRD_CODE', sa.String(length=13), nullable=False, comment='商品コード'),
    sa.Column('PRD_NAME', sa.String(length=50), nullable=False, comment='商品名称'),
    sa.Column('PRD_PRICE', sa.Integer(), nullable=False, comment='商品単価'),
    sa.Column('TAX_CD', sa.String(length=2), nullable=True, comment='消費税区分'),
    sa.ForeignKeyConstraint(['PRD_ID'], ['product_master.PRD_ID'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['TRD_ID'], ['transactions.TRD_ID'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('TRD_ID', 'DTL_ID'),
    comment='取引明細'
    )
    op.create_index(op.f('ix_transaction_details_PRD_ID'), 'transaction_details', ['PRD_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_details_PRD_ID'), table_name='transaction_details')
    op.drop_table('transaction_details')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_product_master_CODE'), table_name='product_master')
    op.drop_table('product_master')
    # ### end Alembic commands ###

